### ISSUE TITLE
Changes to repository structure and essential files

### ISSUE THREAD

**Issue by wreckoner** [ssoubhik/HospitalRecordSystem#1]
Make the following changes to the repository:

1. Change the root directory to `HRS`. `manage.py` should be at the root level
2. Add a `gitignore.py` file. Use the template file at https://github.com/github/gitignore/blob/main/Python.gitignore
3. Add a `requirements.txt` file to the repository. You can create the file using the command `pip freeze > requirements.txt`

**Comment by ssoubhik** [comment]
I have changed the Root Directory and also added .gitignore & requirements.txt files.
So, I'm closing the issue.
